config/routes.rb
Rails.application.routes.draw do
  resources :books

  root 'books#index'

end

app/models/book.rb
class Book < ActiveRecord::Base

  ## Validations ##
  validates :title, :price, :author_names, :description, presence: true

  ## Scope ##
  scope :published_books, -> { where(published: true) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  http_basic_authenticate_with name: "demo", password: "demo"
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    page   = (params[:page].present? && params[:page].to_i > 0)? params[:page] : 1
    @books = Book.published_books.page(page).per(10)
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :description, :published, :price, :author_names)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.slim
= form_for(@book, :html => { :class => "form-horizontal", :role => "form" }) do |f|
  - if @book.errors.any?
    .alert.alert-danger.alert-dismissable role="alert"
      button.close type="button" data-dismiss="alert"
        span aria-hidden="true"
          | &times;
        span.sr-only
          | Close
      h4= "#{pluralize(@book.errors.count,"error")} prohibited this book from being saved:"
      ul
        - @book.errors.full_messages.each do |msg|
          li= msg
  .form-group
    = f.label :title, :class => "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :title, :class => "form-control"
  .form-group
    = f.label :description, :class => "col-sm-2 control-label"
    .col-sm-10
      = f.text_area :description, :class => "form-control"
  .form-group
    = f.label :published, :class => "col-sm-2 control-label"
    .col-sm-10
      = f.check_box :published, :class => "form-control"
  .form-group
    = f.label :price, :class => "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :price, :class => "form-control"
  .form-group
    = f.label :author_names, :class => "col-sm-2 control-label"
    .col-sm-10
      = f.text_area :author_names, :class => "form-control"
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit :class => "btn btn-primary"

app/views/books/edit.html.slim
.page-header
  = link_to books_path, :class => 'btn btn-default' do
    span.glyphicon.glyphicon-list-alt
    |  Back 
  = link_to @book, :class => 'btn btn-primary' do
    span.glyphicon.glyphicon-info-sign
    |  Show 
  h1
    | Editing 
    | book

= render 'form'

app/views/books/index.html.slim
.page-header
  = link_to new_book_path, :class => 'btn btn-primary' do 
    span.glyphicon.glyphicon-plus
    |  New Book
  h1
    | Listing books

.table-responsive
  table.table.table-striped.table-bordered.table-hover
    thead
      tr
        th
          | Title
        th
          | Description
        th
          | Published
        th
          | Price
        th
          | Author names
        th
        th
        th
    tbody
      - @books.each do | book |
        tr
          td
            = book.title
          td
            = book.description
          td
            = book.published
          td
            = book.price
          td
            = book.author_names
          td
            = link_to 'Show', book
          td
            = link_to 'Edit', edit_book_path(book) 
          td
            = link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } 

= paginate @books

app/views/books/new.html.slim
.page-header
  = link_to books_path, :class => 'btn btn-default' do 
    span.glyphicon.glyphicon-list-alt
    |  Back 
  h1
    | New 
    | book

= render 'form'

app/views/books/show.html.slim
.page-header
  = link_to books_path, :class => 'btn btn-default' do 
    span.glyphicon.glyphicon-list-alt
    |  Back 
  = link_to edit_book_path(@book), :class => 'btn btn-primary' do 
    span.glyphicon.glyphicon-pencil
    |  Edit 
  h1
    | Show book
dl.dl-horizontal
  dt
    | Title:
  dd
    = @book.title
  dt
    | Description:
  dd
    = @book.description
  dt
    | Published:
  dd
    = @book.published
  dt
    | Price:
  dd
    = @book.price
  dt
    | Author names:
  dd
    = @book.author_names

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=edge"
    meta name="viewport" content="width=device-width, initial-scale=1"
    meta name="description" content=""
    meta name="author" content=""
    title
      | Demo Project
    /! HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
    /[if lt IE 9]
      = javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    nav.navbar.navbar-inverse.navbar-fixed-top role="navigation"
      .container
        .navbar-header
          button.navbar-toggle.collapsed type="button" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"
            span.sr-only
              | Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
          = link_to "Demo Project", root_path, :class => "navbar-brand"
        #navbar.collapse.navbar-collapse
          ul.nav.navbar-nav
            li.active
              = link_to "Home", root_path
    .container
      - flash.each do |name, msg|
        = content_tag :div, :class => "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", :role => "alert" do
          button.close type="button" data-dismiss="alert"
            span aria-hidden="true"
              | &times;
            span.sr-only
              | Close
          = msg
      = yield